### ISSUE TITLE
Colab runs out of memory while generating bulk embeddings

### ISSUE THREAD

**Issue by deven367** [JohnGiorgi/DeCLUTR#186]
Hello,

I am trying to use DeCLUTR for my thesis where I wish to generate bulk embeddings (around 23k sentences). Once the model is done generating 3.5k embeddings, Google Colab simply crashes and reloads the runtime. Is there any work around for this?

Thanks,
Deven

**Comment by JohnGiorgi** [comment]
Hi @deven367,

Is it crashing because you use up all the available RAM? VRAM? I am able to create 3.5K 768 dimensional embedding with `torch` on colab using either the RAM or VRAM without any issues.

```python
import torch

_ = torch.rand(3500, 768)  # no crash
# OR, for GPU
# matrix = torch.rand(3500, 768, device=torch.cuda.current_device())
```

Maybe if you could link a colab notebook with the minimum amount of code needed to trigger the error I could take a look. In short though, this sounds like a colab problem and not a DeCLUTR problem.

**Comment by deven367** [comment]
https://colab.research.google.com/drive/1zzAciLi8oFHn61ADCt1Z6xzRgG6gMjJw#scrollTo=0wNYDQ7-xC5P

Here's the link to my notebook. I haven't made any particular changes. I face this issue while generating embeddings for these files.
https://github.com/deven367/thesis/blob/main/datasets/cleaned_novels/Ulysses_cleaned.txt
https://github.com/deven367/thesis/blob/main/datasets/cleaned_novels/Pride%20and%20Prejudice_cleaned.txt


![image](https://user-images.githubusercontent.com/31466137/108146707-aaa34280-709b-11eb-9497-3e5c10ce70b4.png)

Please do let me know if I am doing something wrong over here.

Thanks!

**Comment by JohnGiorgi** [comment]
I think I understand what's going on. When we bulk-embed stuff using the AllenNLP `predict` it is creating [`Instance`](https://docs.allennlp.org/v1.0.0rc3/api/data/instance/) objects under the hood (that is what is shown in your screenshot). These objects are actually quite big, and take up a lot of RAM, and eventually crash Colab. I think this problem is mostly solved in `allennlp>=2.0.0`. I have begun the process of updating DeCLUTR to support `allennlp>=2.0.0` but am not done yet.

For now, what if you use the first option mentioned in the notebook (1. __As a library__: import and initialize an object from this repo, which can be used to embed sentences/paragraphs.). This should be as easy as:

```python
from declutr import Encoder

# This can be a path on disk to a model you have trained yourself OR
# the name of one of our pretrained models.
pretrained_model_or_path = "declutr-small"

text = [
    "A smiling costumed woman is holding an umbrella.",
    "A happy woman in a fairy costume holds an umbrella.",
    "A soccer game with multiple males playing.",
    "Some men are playing a sport.",
]

encoder = Encoder(pretrained_model_or_path, cuda_device=cuda_device)
embeddings = encoder(text, batch_size=32)
```

Otherwise, you could use the second option ("2. __🤗 Transformers__: load our pretrained model with the [🤗 Transformers library](https://github.com/huggingface/transformers)."). You might need to wrap some of it up in a function and then call that function in a loop, accumulating embeddings as you go. Something like:

```python
import torch
from scipy.spatial.distance import cosine

from transformers import AutoModel, AutoTokenizer

# Load the model
tokenizer = AutoTokenizer.from_pretrained("johngiorgi/declutr-small")
model = AutoModel.from_pretrained("johngiorgi/declutr-small")
model = model.to(device)

def embed(tokenizer, model, text):
    inputs = tokenizer(text, padding=True, truncation=True, return_tensors="pt")
    
    # Put the tensors on the GPU, if available
    for name, tensor in inputs.items():
        inputs[name] = tensor.to(model.device)

    # Embed the text
    with torch.no_grad():
        sequence_output, _ = model(**inputs, output_hidden_states=False)

    # Mean pool the token-level embeddings to get sentence-level embeddings
    embeddings = torch.sum(
        sequence_output * inputs["attention_mask"].unsqueeze(-1), dim=1
    ) / torch.clamp(torch.sum(inputs["attention_mask"], dim=1, keepdims=True), min=1e-9)
    embeddings = embeddings.cpu()

    return embeddings

# Could do a list of lists to batch input or implement batching another way
text = [
    ["A smiling costumed woman is holding an umbrella.",
     "A happy woman in a fairy costume holds an umbrella.",
     "A soccer game with multiple males playing.",
     "Some men are playing a sport."]
]
embeddings = []
for batch in text:
    embeddings.append(embed(tokenizer, model, batch))
embeddings = torch.cat(embeddings)
```

**Comment by deven367** [comment]
Using the enconder function directly did work out. Thanks John! Is there a way to directly use SentEval on already generated embeddings?

**Comment by JohnGiorgi** [comment]
> Using the enconder function directly did work out. Thanks John! 

Great!

> Is there a way to directly use SentEval on already generated embedding?

Hmm, not sure what you mean. Take a look at SentEval's [documentation](https://github.com/facebookresearch/SentEval). You will need to write a function [`batcher`](https://github.com/facebookresearch/SentEval#2-batcherparams-batch) that takes the input text of the various tasks and returns a vector. We have an example notebook that may be helpful [here](https://colab.research.google.com/github/JohnGiorgi/DeCLUTR/blob/master/notebooks/evaluating.ipynb), and a SentEval script [here](https://github.com/JohnGiorgi/DeCLUTR/blob/master/scripts/run_senteval.py).

**Comment by deven367** [comment]
I mean, I have already saved the embeddings as .npy arrays

**Comment by JohnGiorgi** [comment]
It is likely possible. I would take a look at the SentEval docs. It is not something this repo is setup for if that is what you are asking.

**Comment by deven367** [comment]
Oh okay! I'll take a look at it. Thank you.

**Comment by JohnGiorgi** [comment]
No worries! I think the original issue has been addressed so I will close this. Please re-open this issue or open an additional issue if you get stuck with anything DeCLUTR-specific!
