### ISSUE TITLE
Document Embedding

### ISSUE THREAD

**Issue by FL33TW00D** [JohnGiorgi/DeCLUTR#193]
Hi @JohnGiorgi,
Thanks for releasing these brilliant models, sci-base is exactly what I was looking for and its producing great results. I am looking for your thoughts on maximising performance on documents. I have a range of passages describing an item, and I am wondering of the best way of combining the embeddings to retrain maximum information.

Each of these passages is between 10 and 500 words long. Since SciBERT was primarily trained with 128 length tokens and 512 for the latter part of training, I was wondering what would be the best strategy for providing the model longer information? Providing each passage as is with truncation? Or segmenting into 128 length segments? And would mean pooling at the end be advised?

Many Thanks,
Chris

**Comment by JohnGiorgi** [comment]
Hi @FL33TW00D 

Wow, that’s great! Super happy to hear `declutr-sci-base` is working well for you. I would be very curious to hear about how you are using it if you are comfortable sharing.

Hmm, if I understand your question, you are embedding text up to 500 words long. I think you have two options:

1) Pass the text straight to `declutr-sci-base` without modification — it was trained on passages that ranged in length from 32-512 wordpieces, just like the other DeCLUTR models.
2) Split text up into chunks, embed each chunk, and combine the embeddings some way, as you suggest. Mean pooling is a perfectly reasonable way to combine these embeddings — in practice, I find that it is hard to beat.

I guess you will just have to try each and see which works better for your use case, but I would suspect 1) to work better as the model has the full context when embedding (not to mention it's easier to implement).

One thing I find really helpful is to look at the histogram of text lengths. This can help you decide whether truncating is worth it. E.g. if 99% of the text is less than X number of tokens, it would be worthwhile to truncate to length X (potentially large speed boost with negligible cost to performance). To give you a for-instance, we use `declutr-sci-base` ourselves to do [semantic searching on PubMed Abstracts](https://github.com/PathwayCommons/semantic-search). We set the max length to 384 wordpieces because we found that speeds things up without sacrificing too much performance (the majority of abstracts are 384 wordpieces tokens or shorter)

I hope this helps! Feel free to ask follow-up questions.

**Comment by FL33TW00D** [comment]
Hi @JohnGiorgi,
Thanks for the fast response!

To give a little more context on the use case, I am attempting to create meaningful embeddings to describe medications based on their textual data from both PubChem & OpenFDA, for example:
https://pubchem.ncbi.nlm.nih.gov/compound/174174#section=Pharmacology-and-Biochemistry
https://api.fda.gov/drug/label.json?search=openfda.generic_name:%22atropine%22

As you can see, these are made up of many fields, such as Pharmacology and Mechanism of Action. The reason for my query was due to the MOA entries typically being quite short, and I didn't know if it was worth doing some smart combinations based on length to reduce the negative effects of mean pooling too many embeddings.

Thanks for the tips about plotting a histogram. 
I hope this makes sense, any input would be greatly appreciated!

Many Thanks,
Chris

**Comment by JohnGiorgi** [comment]
@FL33TW00D 

Okay, gotcha. Yeah based on that histogram I would probably be truncating just below 500 tokens. Or to be more precise, you could check where the 90, 95 and 99 percentiles are and then make the decision based on that. Truncating on the 90th percentile means less text so faster embedding, but possibly at the cost of embedding quality, 99 percentile is the opposite.

In short, there are many ways you could combine the embeddings, including max/min/mean pooling or concatenation. I think what works best will depend on your specific use case, as well as how many embeddings you are pooling to get your final representation. Ultimately, you may just have to try each and see how its affects ultimate performance. I suspect mean pooling will be difficult to beat, though. You could also try a weighted average if you expect some text sources to be more meaningful or more important to the final representation.

**Comment by FL33TW00D** [comment]
@JohnGiorgi 

Thanks for the insights. I will give weighted averaging a test to see how it effects performance!

Many Thanks,
Chris
