### ISSUE TITLE
How to plot the learning curve  from the output logs created post training of declutr?

### ISSUE THREAD

**Issue by kingafy** [JohnGiorgi/DeCLUTR#234]

**Comment by JohnGiorgi** [comment]
Hi @kingafy,

You might be better off using Tensorboard. We are using AllenNLP 1.1.0 so the relevant documentation is [here](https://docs.allennlp.org/v1.1.0/api/training/tensorboard_writer/).

Otherwise, I am not sure. You would need to parse the logs and plot the data yourself with matplotlib or something comparable.
